http://pandas.pydata.org/pandas-docs/stable/10min.html

# 10 Minutes to pandas

This is a short introduction to pandas, geared mainly for new users. You can see more complex recipes in the [Cookbook](http://pandas.pydata.org/pandas-docs/stable/cookbook.html#cookbook)

Customarily, we import as follows:

In [161]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [162]:
%matplotlib inline

## Object Creation

See the [Data Structure Intro section](http://pandas.pydata.org/pandas-docs/stable/dsintro.html#dsintro)

Creating a Series by passing a list of values, letting pandas create a default integer index:

In [163]:
s = pd.Series([1,3,5,np.nan,6,8])

In [164]:
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a DataFrame by passing a numpy array, with a datetime index and labeled columns:

In [165]:
dates = pd.date_range('20130101', periods=6)

In [166]:
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [167]:
df = pd.DataFrame(np.random.randn(6,4), index=dates, columns=list('ABCD'))

In [168]:
df

                   A         B         C         D
2013-01-01  1.050119 -1.434852 -1.307356 -1.667664
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-03 -0.260240  2.775797 -2.752803  0.132612
2013-01-04  0.392175 -0.223250  0.955377 -0.439613
2013-01-05 -0.950043 -0.253179 -0.161064  0.317251
2013-01-06  0.310767  0.782585 -0.218699 -0.270446

Creating a DataFrame by passing a dict of objects that can be converted to series-like.

In [169]:
df2 = pd.DataFrame({'A':1.,
                   'B':pd.Timestamp('20130102'),
                   'C':pd.Series(1,index=list(range(4)),dtype='float32'),
                   'D':np.array([3]*4,dtype='int32'),
                   'E':pd.Categorical(["test","train","test","train"]),
                   'F':'foo'})

In [170]:
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

Having specific [dtypes](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-dtypes)

In [171]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

If you’re using IPython, tab completion for column names (as well as public attributes) is automatically enabled. Here’s a subset of the attributes that will be completed:

In [172]:
# df2.<TAB>

As you can see, the columns A, B, C, and D are automatically tab completed. E is there as well; the rest of the attributes have been truncated for brevity.

## Viewing Data

See the [Basics section](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics)

See the top & bottom rows of the frame

In [173]:
df.head()

                   A         B         C         D
2013-01-01  1.050119 -1.434852 -1.307356 -1.667664
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-03 -0.260240  2.775797 -2.752803  0.132612
2013-01-04  0.392175 -0.223250  0.955377 -0.439613
2013-01-05 -0.950043 -0.253179 -0.161064  0.317251

In [174]:
df.tail(3)

                   A         B         C         D
2013-01-04  0.392175 -0.223250  0.955377 -0.439613
2013-01-05 -0.950043 -0.253179 -0.161064  0.317251
2013-01-06  0.310767  0.782585 -0.218699 -0.270446

Display the index, columns, and the underlying numpy data

In [175]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [176]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='str')

In [177]:
df.values

array([[ 1.05011945, -1.43485235, -1.30735591, -1.66766361],
       [ 0.15223246, -0.39575827,  0.13860733, -0.19837575],
       [-0.26024046,  2.77579662, -2.75280339,  0.13261236],
       [ 0.39217472, -0.22324956,  0.95537675, -0.4396132 ],
       [-0.95004291, -0.25317881, -0.16106402,  0.31725053],
       [ 0.31076708,  0.78258461, -0.2186993 , -0.27044574]])

Describe shows a quick statistic summary of your data

In [178]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.115835  0.208557 -0.557656 -0.354373
std    0.673217  1.441241  1.298226  0.700230
min   -0.950043 -1.434852 -2.752803 -1.667664
25%   -0.157122 -0.360113 -1.035192 -0.397321
50%    0.231500 -0.238214 -0.189882 -0.234411
75%    0.371823  0.531126  0.063689  0.049865
max    1.050119  2.775797  0.955377  0.317251

Transposing your data

In [179]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A    1.050119    0.152232   -0.260240    0.392175   -0.950043    0.310767
B   -1.434852   -0.395758    2.775797   -0.223250   -0.253179    0.782585
C   -1.307356    0.138607   -2.752803    0.955377   -0.161064   -0.218699
D   -1.667664   -0.198376    0.132612   -0.439613    0.317251   -0.270446

Sorting by an axis

In [180]:
df.sort_index(axis=1, ascending=False)

                   D         C         B         A
2013-01-01 -1.667664 -1.307356 -1.434852  1.050119
2013-01-02 -0.198376  0.138607 -0.395758  0.152232
2013-01-03  0.132612 -2.752803  2.775797 -0.260240
2013-01-04 -0.439613  0.955377 -0.223250  0.392175
2013-01-05  0.317251 -0.161064 -0.253179 -0.950043
2013-01-06 -0.270446 -0.218699  0.782585  0.310767

Sorting by value

In [181]:
df.sort_values(by='B')

                   A         B         C         D
2013-01-01  1.050119 -1.434852 -1.307356 -1.667664
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-05 -0.950043 -0.253179 -0.161064  0.317251
2013-01-04  0.392175 -0.223250  0.955377 -0.439613
2013-01-06  0.310767  0.782585 -0.218699 -0.270446
2013-01-03 -0.260240  2.775797 -2.752803  0.132612

## Selection

**Note:** While standard Python / Numpy expressions for selecting and setting are intuitive and come in handy for interactive work, for production code, we recommend the optimized pandas data access methods, .at, .iat, .loc, .iloc and .ix.

See the indexing documentation [Indexing and Selecting Data](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing) and [MultiIndex / Advanced Indexing](http://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced)

### Getting

Selecting a single column, which yields a Series, equivalent to df.A

In [182]:
df['A']

2013-01-01    1.050119
2013-01-02    0.152232
2013-01-03   -0.260240
2013-01-04    0.392175
2013-01-05   -0.950043
2013-01-06    0.310767
Freq: D, Name: A, dtype: float64

Selecting via [], which slices the rows.

In [183]:
df[0:3]

                   A         B         C         D
2013-01-01  1.050119 -1.434852 -1.307356 -1.667664
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-03 -0.260240  2.775797 -2.752803  0.132612

In [184]:
df['20130102':'20130104']

                   A         B         C         D
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-03 -0.260240  2.775797 -2.752803  0.132612
2013-01-04  0.392175 -0.223250  0.955377 -0.439613

### Selection by Label

See more in [Selection by Label](Selection by Label)

For getting a cross section using a label

In [185]:
df.loc[dates[0]]

A    1.050119
B   -1.434852
C   -1.307356
D   -1.667664
Name: 2013-01-01 00:00:00, dtype: float64

Selection by Label

In [186]:
df.loc[:,['A','B']]

                   A         B
2013-01-01  1.050119 -1.434852
2013-01-02  0.152232 -0.395758
2013-01-03 -0.260240  2.775797
2013-01-04  0.392175 -0.223250
2013-01-05 -0.950043 -0.253179
2013-01-06  0.310767  0.782585

Showing label slicing, both endpoints are included

In [187]:
df.loc['20130102':'20130104',['A','B']]

                   A         B
2013-01-02  0.152232 -0.395758
2013-01-03 -0.260240  2.775797
2013-01-04  0.392175 -0.223250

Reduction in the dimensions of the returned object

In [188]:
df.loc['20130102',['A','B']]

A    0.152232
B   -0.395758
Name: 2013-01-02 00:00:00, dtype: float64

For getting a scalar value

In [189]:
df.loc[dates[0],'A']

np.float64(1.050119449192121)

### Selection by Position

See more in [Selection by Position](http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-integer)

Select via the position of the passed integers

In [190]:
df.iloc[3]

A    0.392175
B   -0.223250
C    0.955377
D   -0.439613
Name: 2013-01-04 00:00:00, dtype: float64

By integer slices, acting similar to numpy/python

In [191]:
df.iloc[3:5,0:2]

                   A         B
2013-01-04  0.392175 -0.223250
2013-01-05 -0.950043 -0.253179

By lists of integer position locations, similar to the numpy/python style

In [192]:
df.iloc[[1,2,4],[0,2]]

                   A         C
2013-01-02  0.152232  0.138607
2013-01-03 -0.260240 -2.752803
2013-01-05 -0.950043 -0.161064

For slicing rows explicitly

In [193]:
df.iloc[1:3,:]

                   A         B         C         D
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-03 -0.260240  2.775797 -2.752803  0.132612

For slicing columns explicitly

In [194]:
df.iloc[:,1:3]

                   B         C
2013-01-01 -1.434852 -1.307356
2013-01-02 -0.395758  0.138607
2013-01-03  2.775797 -2.752803
2013-01-04 -0.223250  0.955377
2013-01-05 -0.253179 -0.161064
2013-01-06  0.782585 -0.218699

For getting a value explicitly

In [195]:
df.iloc[1,1]

np.float64(-0.3957582651676756)

For getting fast access to a scalar (equiv to the prior method)

In [196]:
df.iat[1,1]

np.float64(-0.3957582651676756)

## Boolean Indexing

Using a single column’s values to select data.

In [197]:
df[df.A > 0]

                   A         B         C         D
2013-01-01  1.050119 -1.434852 -1.307356 -1.667664
2013-01-02  0.152232 -0.395758  0.138607 -0.198376
2013-01-04  0.392175 -0.223250  0.955377 -0.439613
2013-01-06  0.310767  0.782585 -0.218699 -0.270446

A where operation for getting.

In [198]:
df[df > 0]

                   A         B         C         D
2013-01-01  1.050119       NaN       NaN       NaN
2013-01-02  0.152232       NaN  0.138607       NaN
2013-01-03       NaN  2.775797       NaN  0.132612
2013-01-04  0.392175       NaN  0.955377       NaN
2013-01-05       NaN       NaN       NaN  0.317251
2013-01-06  0.310767  0.782585       NaN       NaN

Using the isin() method for filtering:

In [199]:
df2 = df.copy()

In [200]:
df2['E'] = ['one','one', 'two','three','four','three']

In [201]:
df2

                   A         B         C         D      E
2013-01-01  1.050119 -1.434852 -1.307356 -1.667664    one
2013-01-02  0.152232 -0.395758  0.138607 -0.198376    one
2013-01-03 -0.260240  2.775797 -2.752803  0.132612    two
2013-01-04  0.392175 -0.223250  0.955377 -0.439613  three
2013-01-05 -0.950043 -0.253179 -0.161064  0.317251   four
2013-01-06  0.310767  0.782585 -0.218699 -0.270446  three

In [202]:
df2[df2['E'].isin(['two','four'])]

                   A         B         C         D     E
2013-01-03 -0.260240  2.775797 -2.752803  0.132612   two
2013-01-05 -0.950043 -0.253179 -0.161064  0.317251  four

## Setting

Setting a new column automatically aligns the data by the indexes

In [203]:
s1 = pd.Series([1,2,3,4,5,6], index=pd.date_range('20130102',periods=6))

In [204]:
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [205]:
df['F'] = s1

Setting values by label

In [206]:
df.at[dates[0],'A'] = 0

Settomg values by position

In [207]:
df.iat[0,1] = 0

Setting by assigning with a numpy array

In [208]:
df.loc[:,'D'] = np.array([5] * len(df))

The result of the prior setting operations

In [209]:
df

                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -1.307356  5.0  NaN
2013-01-02  0.152232 -0.395758  0.138607  5.0  1.0
2013-01-03 -0.260240  2.775797 -2.752803  5.0  2.0
2013-01-04  0.392175 -0.223250  0.955377  5.0  3.0
2013-01-05 -0.950043 -0.253179 -0.161064  5.0  4.0
2013-01-06  0.310767  0.782585 -0.218699  5.0  5.0

A where operation with setting.

In [210]:
df2 = df.copy()

In [211]:
df2[df2 > 0] = -df2

In [212]:
df2

                   A         B         C    D    F
2013-01-01  0.000000  0.000000 -1.307356 -5.0  NaN
2013-01-02 -0.152232 -0.395758 -0.138607 -5.0 -1.0
2013-01-03 -0.260240 -2.775797 -2.752803 -5.0 -2.0
2013-01-04 -0.392175 -0.223250 -0.955377 -5.0 -3.0
2013-01-05 -0.950043 -0.253179 -0.161064 -5.0 -4.0
2013-01-06 -0.310767 -0.782585 -0.218699 -5.0 -5.0

## Missing Data

pandas primarily uses the value np.nan to represent missing data. It is by default not included in computations. See the Missing Data section

Reindexing allows you to change/add/delete the index on a specified axis. This returns a copy of the data.

In [213]:
df1 = df.reindex(index=dates[0:4], columns=list(df.columns) + ['E'])

In [214]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [215]:
df1

                   A         B         C    D    F    E
2013-01-01  0.000000  0.000000 -1.307356  5.0  NaN  1.0
2013-01-02  0.152232 -0.395758  0.138607  5.0  1.0  1.0
2013-01-03 -0.260240  2.775797 -2.752803  5.0  2.0  NaN
2013-01-04  0.392175 -0.223250  0.955377  5.0  3.0  NaN

To drop any rows that have missing data.

In [216]:
df1.dropna(how='any')

                   A         B         C    D    F    E
2013-01-02  0.152232 -0.395758  0.138607  5.0  1.0  1.0

Filling missing data

In [217]:
df1.fillna(value=5)

                   A         B         C    D    F    E
2013-01-01  0.000000  0.000000 -1.307356  5.0  5.0  1.0
2013-01-02  0.152232 -0.395758  0.138607  5.0  1.0  1.0
2013-01-03 -0.260240  2.775797 -2.752803  5.0  2.0  5.0
2013-01-04  0.392175 -0.223250  0.955377  5.0  3.0  5.0

To get the boolean mask where values are nan

In [218]:
pd.isnull(df1)

                A      B      C      D      F      E
2013-01-01  False  False  False  False   True  False
2013-01-02  False  False  False  False  False  False
2013-01-03  False  False  False  False  False   True
2013-01-04  False  False  False  False  False   True

## Operations

See the [Basic section on Binary Ops](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-binop)

### Stats

Operations in general exclude missing data.

Performing a descriptive statistic

In [219]:
df.mean()

A   -0.059185
B    0.447699
C   -0.557656
D    5.000000
F    3.000000
dtype: float64

Same operation on the other axis

In [220]:
df.mean(1)

/var/folders/hw/cty74w8s3fz2p3lx38rkx1b40000gn/T/ipykernel_80723/3808537418.py:1: Pandas4Warning: Starting with pandas version 4.0 all arguments of mean will be keyword-only.
  df.mean(1)

2013-01-01    0.923161
2013-01-02    1.179016
2013-01-03    1.352551
2013-01-04    1.824860
2013-01-05    1.527143
2013-01-06    2.174930
Freq: D, dtype: float64

Operating with objects that have different dimensionality and need alignment. In addition, pandas automatically broadcasts along the specified dimension.

In [221]:
s = pd.Series([1,3,5,np.nan,6,8], index=dates).shift(2)

In [222]:
s

2013-01-01    NaN
2013-01-02    NaN
2013-01-03    1.0
2013-01-04    3.0
2013-01-05    5.0
2013-01-06    NaN
Freq: D, dtype: float64

In [223]:
df.sub(s, axis='index')

                   A         B         C    D    F
2013-01-01       NaN       NaN       NaN  NaN  NaN
2013-01-02       NaN       NaN       NaN  NaN  NaN
2013-01-03 -1.260240  1.775797 -3.752803  4.0  1.0
2013-01-04 -2.607825 -3.223250 -2.044623  2.0  0.0
2013-01-05 -5.950043 -5.253179 -5.161064  0.0 -1.0
2013-01-06       NaN       NaN       NaN  NaN  NaN

### Apply

Applying functions to the data

In [224]:
df.apply(np.cumsum)

                   A         B         C     D     F
2013-01-01  0.000000  0.000000 -1.307356   5.0   NaN
2013-01-02  0.152232 -0.395758 -1.168749  10.0   1.0
2013-01-03 -0.108008  2.380038 -3.921552  15.0   3.0
2013-01-04  0.284167  2.156789 -2.966175  20.0   6.0
2013-01-05 -0.665876  1.903610 -3.127239  25.0  10.0
2013-01-06 -0.355109  2.686195 -3.345939  30.0  15.0

In [225]:
df.apply(lambda x: x.max() - x.min())

A    1.342218
B    3.171555
C    3.708180
D    0.000000
F    4.000000
dtype: float64

### Histogramming

See more at [Histogramming and Discretization](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-discretization)

In [226]:
s = pd.Series(np.random.randint(0, 7, size=10))

In [227]:
s

0    0
1    0
2    5
3    5
4    2
5    2
6    1
7    1
8    5
9    6
dtype: int64

In [228]:
s.value_counts()

5    3
0    2
2    2
1    2
6    1
Name: count, dtype: int64

### String Methods

Series is equipped with a set of string processing methods in the str attribute that make it easy to operate on each element of the array, as in the code snippet below. Note that pattern-matching in str generally uses [regular expressions](https://docs.python.org/2/library/re.html) by default (and in some cases always uses them). See more at [Vectorized String Methods](http://pandas.pydata.org/pandas-docs/stable/text.html#text-string-methods).

In [229]:
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])

In [230]:
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: str

## Merge

### Concat

pandas provides various facilities for easily combining together Series, DataFrame, and Panel objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

See the [Merging section](http://pandas.pydata.org/pandas-docs/stable/merging.html#merging)

Concatenating pandas objects together with concat():

In [231]:
df = pd.DataFrame(np.random.randn(10, 4))

In [232]:
df

          0         1         2         3
0 -0.344567  0.915771  0.545766 -0.774617
1  0.328985 -0.881637 -1.225165  0.507069
2  0.390024  1.747125 -1.850406  0.463333
3  0.012346  0.239190 -0.820638 -0.190377
4 -0.459090  0.413839  0.823557  0.839043
5 -2.324174 -0.379734 -0.660247 -0.842114
6  0.736668  0.566708 -0.448917 -0.671927
7 -0.296813  0.479599 -0.637330 -0.022188
8 -1.777008 -1.572884  2.126614 -0.591858
9 -0.973964 -0.554870  0.406076 -0.817684

In [233]:
# break it into pieces
pieces = [df[:3], df[3:7], df[7:]]

In [234]:
pd.concat(pieces)

          0         1         2         3
0 -0.344567  0.915771  0.545766 -0.774617
1  0.328985 -0.881637 -1.225165  0.507069
2  0.390024  1.747125 -1.850406  0.463333
3  0.012346  0.239190 -0.820638 -0.190377
4 -0.459090  0.413839  0.823557  0.839043
5 -2.324174 -0.379734 -0.660247 -0.842114
6  0.736668  0.566708 -0.448917 -0.671927
7 -0.296813  0.479599 -0.637330 -0.022188
8 -1.777008 -1.572884  2.126614 -0.591858
9 -0.973964 -0.554870  0.406076 -0.817684

### Join

SQL style merges. See the [Database style joining](http://pandas.pydata.org/pandas-docs/stable/merging.html#merging-join)

In [235]:
left = pd.DataFrame({'key': ['foo', 'foo'], 'lval': [1, 2]})

In [236]:
right = pd.DataFrame({'key': ['foo', 'foo'], 'rval': [4, 5]})

In [237]:
left

   key  lval
0  foo     1
1  foo     2

In [238]:
right

   key  rval
0  foo     4
1  foo     5

In [239]:
pd.merge(left, right, on='key')

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

### Append

Append rows to a dataframe. See the [Appending](http://pandas.pydata.org/pandas-docs/stable/merging.html#merging-concatenation)

In [240]:
df = pd.DataFrame(np.random.randn(8, 4), columns=['A','B','C','D'])

In [241]:
df

          A         B         C         D
0  0.621301 -2.171433  1.387798  0.408833
1 -0.145602  0.621605  0.994168 -0.039365
2 -1.809471  1.578332  1.360270  0.135580
3 -1.434079 -0.217916  1.146639 -0.145348
4 -0.195906 -1.117854  0.104827  0.355623
5 -0.271982  0.945915 -1.798548 -0.084119
6 -1.248015 -0.050841  0.006448 -0.367531
7 -0.688921  1.489911  0.943297 -0.133105

In [242]:
s = df.iloc[3]

In [243]:
#df.concat(s, ignore_index=True)
pd.concat([df, s.to_frame().T], ignore_index=True)

          A         B         C         D
0  0.621301 -2.171433  1.387798  0.408833
1 -0.145602  0.621605  0.994168 -0.039365
2 -1.809471  1.578332  1.360270  0.135580
3 -1.434079 -0.217916  1.146639 -0.145348
4 -0.195906 -1.117854  0.104827  0.355623
5 -0.271982  0.945915 -1.798548 -0.084119
6 -1.248015 -0.050841  0.006448 -0.367531
7 -0.688921  1.489911  0.943297 -0.133105
8 -1.434079 -0.217916  1.146639 -0.145348

## Grouping

By “group by” we are referring to a process involving one or more of the following steps

* **Splitting** the data into groups based on some criteria
* **Applying** a function to each group independently
* **Combining** the results into a data structure

See the [Grouping section](http://pandas.pydata.org/pandas-docs/stable/groupby.html#groupby)

In [244]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar', 'foo', 'bar', 'foo', 'foo'],
                                    'B' : ['one', 'one', 'two', 'three','two', 'two', 'one', 'three'],
                                    'C' : np.random.randn(8),
                                     'D' : np.random.randn(8)})

In [245]:
df

     A      B         C         D
0  foo    one -0.312113 -0.967967
1  bar    one  0.468253  0.728001
2  foo    two  0.280091 -0.520765
3  bar  three -0.170978 -1.513571
4  foo    two  1.645098  0.235313
5  bar    two -0.445132  0.180395
6  foo    one -0.668022 -0.068471
7  foo  three  0.546344  2.278481

Grouping and then applying a function sum to the resulting groups.

In [246]:
df.groupby('A').sum()

                     B         C         D
A
bar        onethreetwo -0.147857 -0.605175
foo  onetwotwoonethree  1.491398  0.956591

In [247]:
df.groupby(['A','B']).sum()

                  C         D
A   B
bar one    0.468253  0.728001
    three -0.170978 -1.513571
    two   -0.445132  0.180395
foo one   -0.980135 -1.036438
    three  0.546344  2.278481
    two    1.925189 -0.285452

## Reshaping

See the sections on [Hierarchical Indexing](http://pandas.pydata.org/pandas-docs/stable/advanced.html#advanced-hierarchical) and [Reshaping](http://pandas.pydata.org/pandas-docs/stable/reshaping.html#reshaping-stacking).

### Stack

In [248]:
tuples = list(zip(*[['bar', 'bar', 'baz', 'baz', 'foo', 'foo', 'qux', 'qux'],
                                ['one', 'two', 'one', 'two', 'one', 'two', 'one', 'two']]))

In [249]:
index = pd.MultiIndex.from_tuples(tuples, names=['first', 'second'])

In [250]:
df = pd.DataFrame(np.random.randn(8, 2), index=index, columns=['A', 'B'])

In [251]:
df2 = df[:4]

In [252]:
df2

                     A         B
first second
bar   one    -0.206643  0.129147
      two     0.569132 -0.943749
baz   one     2.234050  0.144316
      two    -0.389359 -1.145463

The stack() method “compresses” a level in the DataFrame’s columns.

In [253]:
stacked = df2.stack()

In [254]:
stacked

first  second
bar    one     A   -0.206643
               B    0.129147
       two     A    0.569132
               B   -0.943749
baz    one     A    2.234050
               B    0.144316
       two     A   -0.389359
               B   -1.145463
dtype: float64

With a “stacked” DataFrame or Series (having a MultiIndex as the index), the inverse operation of stack() is unstack(), which by default unstacks the **last level**:

In [255]:
stacked.unstack()

                     A         B
first second
bar   one    -0.206643  0.129147
      two     0.569132 -0.943749
baz   one     2.234050  0.144316
      two    -0.389359 -1.145463

In [256]:
stacked.unstack(1)

second        one       two
first
bar   A -0.206643  0.569132
      B  0.129147 -0.943749
baz   A  2.234050 -0.389359
      B  0.144316 -1.145463

In [257]:
stacked.unstack(0)

first          bar       baz
second
one    A -0.206643  2.234050
       B  0.129147  0.144316
two    A  0.569132 -0.389359
       B -0.943749 -1.145463

### Pivot Tables

See the section on [Pivot Tables](http://pandas.pydata.org/pandas-docs/stable/reshaping.html#reshaping-pivot).

In [258]:
df = pd.DataFrame({'A' : ['one', 'one', 'two', 'three'] * 3,
                                    'B' : ['A', 'B', 'C'] * 4,
                                    'C' : ['foo', 'foo', 'foo', 'bar', 'bar', 'bar'] * 2,
                                    'D' : np.random.randn(12),
                                    'E' : np.random.randn(12)})

In [259]:
df

        A  B    C         D         E
0     one  A  foo -0.373681  3.363150
1     one  B  foo  0.122318 -0.587265
2     two  C  foo  0.274396 -1.236658
3   three  A  bar  0.849153  0.003662
4     one  B  bar  0.378170  1.321071
5     one  C  bar  0.565783 -0.008184
6     two  A  foo  0.185406  0.383689
7   three  B  foo  0.894117 -1.009041
8     one  C  foo  2.060859  0.392600
9     one  A  bar -0.627642 -1.094560
10    two  B  bar -1.589862 -1.092741
11  three  C  bar -1.217451  1.317033

We can produce pivot tables from this data very easily:

In [260]:
pd.pivot_table(df, values='D', index=['A', 'B'], columns=['C'])

C             bar       foo
A     B
one   A -0.627642 -0.373681
      B  0.378170  0.122318
      C  0.565783  2.060859
three A  0.849153       NaN
      B       NaN  0.894117
      C -1.217451       NaN
two   A       NaN  0.185406
      B -1.589862       NaN
      C       NaN  0.274396

## Time Series

pandas has simple, powerful, and efficient functionality for performing resampling operations during frequency conversion (e.g., converting secondly data into 5-minutely data). This is extremely common in, but not limited to, financial applications. See the [Time Series section](http://pandas.pydata.org/pandas-docs/stable/timeseries.html#timeseries)

In [261]:
rng = pd.date_range('1/1/2012', periods=100, freq='S')

ValueError: Invalid frequency: S. Failed to parse with error message: ValueError("Invalid frequency: S. Failed to parse with error message: KeyError('S'). Did you mean s?") Did you mean s?

In [102]:
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [ ]:
ts.resample('5Min').sum()

Time zone representation

In [104]:
rng = pd.date_range('3/6/2012 00:00', periods=5, freq='D')

In [105]:
ts = pd.Series(np.random.randn(len(rng)), rng)

In [ ]:
ts

In [107]:
ts_utc = ts.tz_localize('UTC')

In [ ]:
ts_utc


Convert to another time zone

In [ ]:
ts_utc.tz_convert('US/Eastern')


Converting between time span representations

In [110]:
rng = pd.date_range('1/1/2012', periods=5, freq='M')

In [111]:
ts = pd.Series(np.random.randn(len(rng)), index=rng)

In [ ]:
ts

In [113]:
ps = ts.to_period()

In [ ]:
ps

In [ ]:
ps.to_timestamp()

Converting between period and timestamp enables some convenient arithmetic functions to be used. In the following example, we convert a quarterly frequency with year ending in November to 9am of the end of the month following the quarter end:

In [116]:
prng = pd.period_range('1990Q1', '2000Q4', freq='Q-NOV')

In [117]:
ts = pd.Series(np.random.randn(len(prng)), prng)

In [118]:
ts.index = (prng.asfreq('M', 'e') + 1).asfreq('H', 's') + 9

In [ ]:
ts.head()

## Categoricals

Since version 0.15, pandas can include categorical data in a DataFrame. For full docs, see the [categorical introduction](http://pandas.pydata.org/pandas-docs/stable/categorical.html#categorical) and the [API documentation](http://pandas.pydata.org/pandas-docs/stable/api.html#api-categorical).

In [120]:
df = pd.DataFrame({"id":[1,2,3,4,5,6], "raw_grade":['a', 'b', 'b', 'a', 'a', 'e']})

Convert the raw grades to a categorical data type.

In [121]:
df["grade"] = df["raw_grade"].astype("category")

In [ ]:
df["grade"]

Rename the categories to more meaningful names (assigning to Series.cat.categories is inplace!)

In [123]:
df["grade"].cat.categories = ["very good", "good", "very bad"]

Reorder the categories and simultaneously add the missing categories (methods under Series .cat return a new Series per default).

In [124]:
df["grade"] = df["grade"].cat.set_categories(["very bad", "bad", "medium", "good", "very good"])

In [ ]:
df["grade"]

Sorting is per order in the categories, not lexical order.

In [ ]:
df.sort_values(by="grade")

Grouping by a categorical column shows also empty categories.

In [ ]:
df.groupby("grade").size()

## Plotting
[Plotting](http://pandas.pydata.org/pandas-docs/stable/visualization.html#visualization) docs.

In [128]:
ts = pd.Series(np.random.randn(1000), index=pd.date_range('1/1/2000', periods=1000))

In [129]:
ts = ts.cumsum()

In [ ]:
ts.plot()

On DataFrame, plot() is a convenience to plot all of the columns with labels:

In [131]:
df = pd.DataFrame(np.random.randn(1000, 4), index=ts.index,
                  columns=['A', 'B', 'C', 'D'])

In [132]:
df = df.cumsum()

In [ ]:
plt.figure(); df.plot(); plt.legend(loc='best')

## Getting Data In/Out

### CSV
[Writing to a csv file](http://pandas.pydata.org/pandas-docs/stable/io.html#io-store-in-csv)

In [134]:
df.to_csv('foo.csv')

[Reading from a csv file](http://pandas.pydata.org/pandas-docs/stable/io.html#io-read-csv-table)

In [ ]:
pd.read_csv('foo.csv')

### HDF5
Reading and writing to [HDFStores](http://pandas.pydata.org/pandas-docs/stable/io.html#io-hdf5)

Writing to a HDF5 Store

In [136]:
df.to_hdf('foo.h5','df')

Reading from a HDF5 Store

In [ ]:
pd.read_hdf('foo.h5','df')

### Excel

Reading and writing to [MS Excel](http://pandas.pydata.org/pandas-docs/stable/io.html#io-excel)

Writing to an excel file

In [138]:
df.to_excel('foo.xlsx', sheet_name='Sheet1')

Reading from an excel file

In [ ]:
pd.read_excel('foo.xlsx', 'Sheet1', index_col=None, na_values=['NA'])

### Gotchas
If you are trying an operation and you see an exception like:

In [ ]:
if pd.Series([False, True, False]):
    print("I was true")

See [Comparisons](http://pandas.pydata.org/pandas-docs/stable/basics.html#basics-compare) for an explanation and what to do.

See [Gotchas](http://pandas.pydata.org/pandas-docs/stable/gotchas.html#gotchas) as well.