# Chipotle Exercise - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [49]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")

### Step 4. See the first 10 entries

In [4]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [5]:
# Solution 1
# This solution should involve accessing an array
len(chipo)

4622

In [6]:
# Solution 2
# This solution should involve utilizing a function
...
chipo.shape[0]

4622

### Step 6. What is the number of columns in the dataset?

In [7]:
...
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [9]:
print(chipo.columns)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

### Step 8. How is the dataset indexed?

...

### Step 9. Which was the most-ordered item?

In [23]:
# Hint: When sorting values, you can pass ascending = False
most_ordered = (chipo.groupby("item_name")["quantity"].sum().sort_values(ascending=False))
most_ordered.index[0]

'Chicken Bowl'

### Step 10. For the most-ordered item, how many items were ordered?

In [24]:
chipo.groupby("item_name")["quantity"].sum().max()

np.int64(761)

### Step 11. What was the most ordered item in the choice_description column?

In [25]:
most_ordered_choice = (chipo.groupby("choice_description")["quantity"].sum().sort_values(ascending=False))
most_ordered_choice.index[0]

'[Diet Coke]'

### Step 12. For the most-ordered item in choice_description, how many items were ordered?

In [26]:
chipo.groupby("choice_description")["quantity"].sum().max()

np.int64(159)

### Step 13. Turn the item price into a float

In [31]:
chipo['item_price'] = (chipo['item_price'].str.replace("$", "", regex=False).astype(float))

In [32]:
# show the dataframe
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

#### Step 13.a. Check the item price type

In [34]:
chipo['item_name'].dtype

#### Step 13.b. Create a lambda function and change the type of item price

In [50]:
dollarizer = lambda x: float(x.replace("$", ""))
chipo["item_price"] = chipo["item_price"].apply(dollarizer)
# How can we apply a function to a column
...

Ellipsis

#### Step 13.c. Check the item price type

In [51]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

### Step 14. How much was the revenue for the period in the dataset?

In [53]:
## note: the np.round(argument, int) will round the number to the int decimal points
np.round(chipo["item_price"].sum(), 2)

np.float64(34500.16)

### Step 15. How many orders were made in the period?

In [55]:
chipo["order_id"].max()

np.int64(1834)

### Step 16. How many items were ordered in total?

In [56]:
chipo["quantity"].sum()

np.int64(4972)

### Step 17. What is the average revenue amount per order?

In [59]:
np.round((chipo["item_price"].sum())/(chipo["quantity"].sum()), 2)

np.float64(6.94)

### Step 18. How many different items are sold?

In [64]:
chipo["item_name"].nunique()

50

Submit by pushing your code to your repo. Don't forget to git add, commit, and push!